chore: code format

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -13,19 +13,17 @@ env:
     PNAME: agent
 
 jobs:
-    unit_test:
+    format_check:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout current repository
               uses: actions/checkout@v4
               with:
-                fetch-depth: 0
                 path: ${{ env.PNAME }}
 
             - name: Checkout framework repository
               uses: actions/checkout@v4
               with:
-                fetch-depth: 0
                 repository: infinilabs/framework
                 path: framework
 
@@ -33,7 +31,62 @@ jobs:
               uses: actions/checkout@v4
               with:
                 ref: main
-                fetch-depth: 0
+                repository: infinilabs/framework-vendor
+                path: vendor
+
+            - name: Set up go toolchain
+              uses: actions/setup-go@v5
+              with:
+                go-version: ${{ env.GO_VERSION }}
+                check-latest: false
+                cache: true
+
+            - name: Check go toolchain
+              run: go version
+              
+            - name: Run make format
+              shell: bash
+              run: |
+                make format
+                if [ $? -ne 0 ]; then
+                  echo "make format failed, please check make output"
+                  exit 1
+                fi
+
+            - name: Check for changes after format
+              id: check-changes
+              shell: bash
+              run: |
+                if [[ $(git status --porcelain | grep -c " M .*\.go$") -gt 0 ]]; then
+                  echo "go format detected formatting changes"
+                  echo "::set-output name=changes::true"
+                else
+                  echo "go format no changes found"
+                  echo "::set-output name=changes::false"
+                fi
+            
+            - name: Fail workflow if changes after format
+              if: steps.check-changes.outputs.changes == 'true'
+              run: exit 1
+
+    unit_test:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout current repository
+              uses: actions/checkout@v4
+              with:
+                path: ${{ env.PNAME }}
+
+            - name: Checkout framework repository
+              uses: actions/checkout@v4
+              with:
+                repository: infinilabs/framework
+                path: framework
+
+            - name: Checkout framework-vendor
+              uses: actions/checkout@v4
+              with:
+                ref: main
                 repository: infinilabs/framework-vendor
                 path: vendor
 
@@ -74,13 +127,11 @@ jobs:
             - name: Checkout current repository
               uses: actions/checkout@v4
               with:
-                fetch-depth: 0
                 path: ${{ env.PNAME }}
 
             - name: Checkout framework repository
               uses: actions/checkout@v4
               with:
-                fetch-depth: 0
                 repository: infinilabs/framework
                 path: framework
 
@@ -88,7 +139,6 @@ jobs:
               uses: actions/checkout@v4
               with:
                 ref: main
-                fetch-depth: 0
                 repository: infinilabs/framework-vendor
                 path: vendor
 
